spring.application.name=productpricealerttracker
spring.jpa.hibernate.ddl-auto=update

#access.cors.allowed-origin="*"

# SendGrid
# api.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNjI0ZDBjNDQzMTMyODJlNzQzNjM4ZWY2M2E3NjRjODk0MmZhMGVjNmRlNDJhY2IwMmRhMjAwZDc4YWE0NDE2NmQ5YWVlOTIwMThiMjI4NWEiLCJpYXQiOjE3NDYwMzg2NTIuNzU1NTAyLCJuYmYiOjE3NDYwMzg2NTIuNzU1NTA2LCJleHAiOjQ5MDE3MTIyNTIuNzQyOTIsInN1YiI6IjE5MzU5OCIsInNjb3BlcyI6W119.eUTV6A5qRYsaKMct-SyM62-bvuwR3NQeNApdBafyKoZc-QnYyBDlwd3KTlydIaFIfckAzCEKf4AH5V6C3cDjoA
notification.from.email=noreply@test-3m5jgrooyrogdpyo.mlsender.net
#notification.from.email=dfsf


api.token=mlsn.54e59f2a481d1dca55b0aadb2d9d2b9a7bab376c9f1be78290d0142bf599a69f
# testnotification
# eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNjI0ZDBjNDQzMTMyODJlNzQzNjM4ZWY2M2E3NjRjODk0MmZhMGVjNmRlNDJhY2IwMmRhMjAwZDc4YWE0NDE2NmQ5YWVlOTIwMThiMjI4NWEiLCJpYXQiOjE3NDYwMzg2NTIuNzU1NTAyLCJuYmYiOjE3NDYwMzg2NTIuNzU1NTA2LCJleHAiOjQ5MDE3MTIyNTIuNzQyOTIsInN1YiI6IjE5MzU5OCIsInNjb3BlcyI6W119.eUTV6A5qRYsaKMct-SyM62-bvuwR3NQeNApdBafyKoZc-QnYyBDlwd3KTlydIaFIfckAzCEKf4AH5V6C3cDjoA
